services:

  postgres:
    image: postgres:16
    container_name: aroma-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: aroma_cafe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile

    container_name: aroma-backend
    restart: unless-stopped

    depends_on:
      - postgres

    ports:
      - "3000:3000"

    environment:
      PORT: 3000

      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: aroma_cafe
      DB_USER: postgres
      DB_PASSWORD: postgres

      JWT_SECRET: aroma_cafe_secreto_docker

volumes:
  postgres_data:
